<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<doxygen xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="compound.xsd" version="1.13.2" xml:lang="en-US">
  <compounddef id="classgoogletest-catch-exceptions-test_1_1_catch_seh_exceptions_test" kind="class" language="Python" prot="public">
    <compoundname>googletest-catch-exceptions-test::CatchSehExceptionsTest</compoundname>
    <basecompoundref prot="public" virt="non-virtual">gtest_test_utils.TestCase</basecompoundref>
    <sectiondef kind="public-func">
      <memberdef kind="function" id="classgoogletest-catch-exceptions-test_1_1_catch_seh_exceptions_test_1a6c861877cf1d1da5fb43b2405039ace6" prot="public" static="no" const="no" explicit="no" inline="no" virt="non-virtual">
        <type></type>
        <definition>googletest-catch-exceptions-test.CatchSehExceptionsTest.TestSehExceptions</definition>
        <argsstring>(self, test_output)</argsstring>
        <name>TestSehExceptions</name>
        <qualifiedname>googletest-catch-exceptions-test.CatchSehExceptionsTest.TestSehExceptions</qualifiedname>
        <param>
          <type>self</type>
          <defname>self</defname>
        </param>
        <param>
          <type>test_output</type>
          <defname>test_output</defname>
        </param>
        <briefdescription>
        </briefdescription>
        <detaileddescription>
        </detaileddescription>
        <inbodydescription>
        </inbodydescription>
        <location file="build/_deps/googletest-src/googletest/test/googletest-catch-exceptions-test.py" line="88" column="1" bodyfile="build/_deps/googletest-src/googletest/test/googletest-catch-exceptions-test.py" bodystart="88" bodyend="119"/>
      </memberdef>
      <memberdef kind="function" id="classgoogletest-catch-exceptions-test_1_1_catch_seh_exceptions_test_1aa79284eb703713ef890cae35648c1ec8" prot="public" static="no" const="no" explicit="no" inline="no" virt="non-virtual">
        <type></type>
        <definition>googletest-catch-exceptions-test.CatchSehExceptionsTest.testCatchesSehExceptionsWithCxxExceptionsEnabled</definition>
        <argsstring>(self)</argsstring>
        <name>testCatchesSehExceptionsWithCxxExceptionsEnabled</name>
        <qualifiedname>googletest-catch-exceptions-test.CatchSehExceptionsTest.testCatchesSehExceptionsWithCxxExceptionsEnabled</qualifiedname>
        <param>
          <type>self</type>
          <defname>self</defname>
        </param>
        <briefdescription>
        </briefdescription>
        <detaileddescription>
        </detaileddescription>
        <inbodydescription>
        </inbodydescription>
        <location file="build/_deps/googletest-src/googletest/test/googletest-catch-exceptions-test.py" line="120" column="1" bodyfile="build/_deps/googletest-src/googletest/test/googletest-catch-exceptions-test.py" bodystart="120" bodyend="122"/>
      </memberdef>
      <memberdef kind="function" id="classgoogletest-catch-exceptions-test_1_1_catch_seh_exceptions_test_1a22b59a8251148ea6572b15602a446c9d" prot="public" static="no" const="no" explicit="no" inline="no" virt="non-virtual">
        <type></type>
        <definition>googletest-catch-exceptions-test.CatchSehExceptionsTest.testCatchesSehExceptionsWithCxxExceptionsDisabled</definition>
        <argsstring>(self)</argsstring>
        <name>testCatchesSehExceptionsWithCxxExceptionsDisabled</name>
        <qualifiedname>googletest-catch-exceptions-test.CatchSehExceptionsTest.testCatchesSehExceptionsWithCxxExceptionsDisabled</qualifiedname>
        <param>
          <type>self</type>
          <defname>self</defname>
        </param>
        <briefdescription>
        </briefdescription>
        <detaileddescription>
        </detaileddescription>
        <inbodydescription>
        </inbodydescription>
        <location file="build/_deps/googletest-src/googletest/test/googletest-catch-exceptions-test.py" line="123" column="1" bodyfile="build/_deps/googletest-src/googletest/test/googletest-catch-exceptions-test.py" bodystart="123" bodyend="126"/>
      </memberdef>
    </sectiondef>
    <briefdescription>
    </briefdescription>
    <detaileddescription>
<para><verbatim>Tests exception-catching behavior.</verbatim> </para>
    </detaileddescription>
    <inheritancegraph>
      <node id="1">
        <label>googletest-catch-exceptions-test.CatchSehExceptionsTest</label>
        <link refid="classgoogletest-catch-exceptions-test_1_1_catch_seh_exceptions_test"/>
        <childnode refid="2" relation="public-inheritance">
        </childnode>
      </node>
      <node id="2">
        <label>gtest_test_utils.TestCase</label>
      </node>
    </inheritancegraph>
    <collaborationgraph>
      <node id="1">
        <label>googletest-catch-exceptions-test.CatchSehExceptionsTest</label>
        <link refid="classgoogletest-catch-exceptions-test_1_1_catch_seh_exceptions_test"/>
        <childnode refid="2" relation="public-inheritance">
        </childnode>
      </node>
      <node id="2">
        <label>gtest_test_utils.TestCase</label>
      </node>
    </collaborationgraph>
    <location file="build/_deps/googletest-src/googletest/test/googletest-catch-exceptions-test.py" line="85" column="1" bodyfile="build/_deps/googletest-src/googletest/test/googletest-catch-exceptions-test.py" bodystart="85" bodyend="126"/>
    <listofallmembers>
      <member refid="classgoogletest-catch-exceptions-test_1_1_catch_seh_exceptions_test_1a22b59a8251148ea6572b15602a446c9d" prot="public" virt="non-virtual"><scope>googletest-catch-exceptions-test::CatchSehExceptionsTest</scope><name>testCatchesSehExceptionsWithCxxExceptionsDisabled</name></member>
      <member refid="classgoogletest-catch-exceptions-test_1_1_catch_seh_exceptions_test_1aa79284eb703713ef890cae35648c1ec8" prot="public" virt="non-virtual"><scope>googletest-catch-exceptions-test::CatchSehExceptionsTest</scope><name>testCatchesSehExceptionsWithCxxExceptionsEnabled</name></member>
      <member refid="classgoogletest-catch-exceptions-test_1_1_catch_seh_exceptions_test_1a6c861877cf1d1da5fb43b2405039ace6" prot="public" virt="non-virtual"><scope>googletest-catch-exceptions-test::CatchSehExceptionsTest</scope><name>TestSehExceptions</name></member>
    </listofallmembers>
  </compounddef>
</doxygen>
